FROM php:8.1-fpm-alpine AS build

WORKDIR /spid-cie-php

RUN apk add php-session \
    php-tokenizer \
    php-xml \
    php-ctype \
    php-curl \
    php-dom \
    php-fileinfo \
    php-pgsql \
    php-mbstring \
    php-openssl \
    php-session \
    php-tokenizer \
    php-xml \
    php-ctype \
    php-xmlwriter \
    php-simplexml \
    php-gmp \
    gmp-dev \
    php-bcmath \
    composer \
    git

RUN apk add postgresql-dev \
 && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
 && docker-php-ext-install pdo pdo_pgsql pgsql

RUN docker-php-ext-install bcmath \
    gmp

COPY docker/docker-fpm.ini /usr/local/etc/php/conf.d/docker-fpm.ini
COPY docker/www.conf /usr/local/etc/php-fpm.d/www.conf

CMD ["php-fpm", "--nodaemonize"]
